#!/bin/sh
#
# @name Gazebo x500 with downward realsense camera
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_realsense}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# param set-default SYS_HAS_GPS 0
# param set-default SIM_GPS_USED 0
# param set-default EKF2_GPS_CTRL 2
# param set-default EKF2_HGT_REF 1
# param set-default EKF2_EV_CTRL 2
# param set-default EKF2_EV_DELAY 1
param set-default NAV_DLL_ACT 0

param set-default MPC_XY_VEL_MAX 12
param set-default MPC_VEL_MANUAL 12
param set-default MPC_XY_CRUISE 12
param set-default MC_YAWRATE_MAX 60

# VIO
param set-default EKF2_EV_CTRL 3
param set-default EKF2_HGT_REF 1
param set-default EKF2_EV_DELAY 0.1

param set-default EKF2_EV_POS_X 0.12
param set-default EKF2_EV_POS_Y 0.03
param set-default EKF2_EV_POS_Z 0.1
param set-default SDLOG_MODE 1

